using System;

namespace DNA.Runtime.InteropServices.Win32
{
	[Flags]
	public enum FileDevice : uint
	{
		Beep = 1U,
		CDRom = 2U,
		CDRomFileSystem = 3U,
		Controller = 4U,
		DataLink = 5U,
		DFS = 6U,
		Disk = 7U,
		DiskFileSystem = 8U,
		FileSystem = 9U,
		InPortPort = 10U,
		Keyboard = 11U,
		MailSlot = 12U,
		MidiIn = 13U,
		MidiOut = 14U,
		Mouse = 15U,
		MultiUNCProvider = 16U,
		NamedPipe = 17U,
		Network = 18U,
		NetworkBrowser = 19U,
		NetworkFileSystem = 20U,
		Null = 21U,
		ParallelPort = 22U,
		PhysicalNetCard = 23U,
		Printer = 24U,
		Scanner = 25U,
		SerialMousePort = 26U,
		SerialPort = 27U,
		Screen = 28U,
		Sound = 29U,
		Streams = 30U,
		Tape = 31U,
		TapeFileSystem = 32U,
		Transport = 33U,
		Unknown = 34U,
		Video = 35U,
		VirtualDisk = 36U,
		WaveIn = 37U,
		WaveOut = 38U,
		Port8042 = 39U,
		NetworkRedirector = 40U,
		Battery = 41U,
		BusExtender = 42U,
		Modem = 43U,
		VDM = 44U,
		MassStorage = 45U,
		SMB = 46U,
		KS = 47U,
		Changer = 48U,
		SmartCard = 49U,
		ACPi = 50U,
		DVD = 51U,
		FullScreenVideo = 52U,
		DFSFileSystem = 53U,
		DFSVolume = 54U,
		SerEnum = 55U,
		TermsRV = 56U,
		KSec = 57U,
		FIPS = 58U,
		InFinIBand = 59U
	}
}
