using System;

namespace DNA.Drawing.Imaging.Photoshop
{
	public enum ResourceID
	{
		Undefined,
		MacPrintInfo = 1001,
		ResolutionInfo = 1005,
		AlphaChannelNames,
		DisplayInfo,
		Caption,
		BorderInfo,
		BgColor,
		PrintFlags,
		MultiChannelHalftoneInfo,
		ColorHalftoneInfo,
		DuotoneHalftoneInfo,
		MultiChannelTransferFunctions,
		ColorTransferFunctions,
		DuotoneTransferFunctions,
		DuotoneImageInfo,
		BlackWhiteRange,
		EPSOptions = 1021,
		QuickMaskInfo,
		LayerStateInfo = 1024,
		WorkingPathUnsaved,
		LayersGroupInfo,
		IPTC_NAA = 1028,
		RawFormatImageMode,
		JPEGQuality,
		GridGuidesInfo = 1032,
		ThumbnailBgr,
		CopyrightInfo,
		URL,
		ThumbnailRgb,
		GlobalAngle,
		ColorSamplers,
		ICCProfile,
		Watermark,
		ICCUntagged,
		EffectsVisible,
		SpotHalftone,
		DocumentSpecific,
		UnicodeAlphaNames,
		IndexedColorTableCount,
		TransparentIndex,
		GlobalAltitude = 1049,
		Slices,
		WorkflowURL,
		JumpToXPEP,
		AlphaIdentifiers,
		URLList,
		VersionInfo = 1057,
		Unknown4,
		XMLInfo = 1060,
		CaptionDigest,
		PrintScale,
		PixelAspectRatio = 1064,
		PathInfo = 2000,
		ClippingPathName = 2999,
		PrintFlagsInfo = 10000
	}
}
